version: "3.1"

services:
  tp-poo:
    container_name: tp-poo-intaller
    image: tp-poo
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./app:/var/www/
    command: composer install --dev
  
  tp-poo-tester:
    container_name: tp-poo-tester
    image: tp-poo
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./app:/var/www/